on:
    schedule:
        - cron: '*/5 * * * *'

jobs:
    unit-test-nightly-cache:
        name: Unit tests
        runs-on: ubuntu-latest
        timeout-minutes: 10
        needs: install-dependencies
        steps:
          - uses: actions/checkout@v2
            with:
              fetch-depth: 0
          
          - name: Restore node_modules cache
            id: yarn-cache
            uses: actions/cache@v2
            with:
              path: node_modules
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          
          - name: Cache Jest nightly
            id: cache-jest-cache
            uses: actions/cache@v2
            with:
                path: /home/runner/work/gha-test/gha-test/.jest-cache
                key: ${{ runner.os }}-${{ matrix.node-version }}-${{ steps.date.outputs.date }}-jest
          
          - name: Start test
            run: yarn test --changedSince=${{ github.event.pull_request.base.sha }} --max-workers=2 --ci --passWithNoTests --bail --coverage --silent
