name: Cache Cron unit tests

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'
    pull_request:
        types:
            - opened
            - reopened
            - labeled
            - unlabeled
            - synchronize
        branches:
             - master

jobs:
    unit-test-nightly-cache:
        name: Unit tests
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
          - uses: actions/checkout@v2
            with:
              fetch-depth: 0
          
          - name: Restore node_modules cache
            id: yarn-cache
            uses: actions/cache@v2
            with:
              path: node_modules
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          
          - name: Get current date
            id: date
            run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
          
          - name: Start test
            working-directory: ./
            shell: bash
            run: yarn test --cacheDirectory="./.jest_cache" --max-workers=2 --ci --passWithNoTests --bail --coverage --silent
          
          - name: Archive unit test cache
            uses: actions/upload-artifact@v3
            with:
              name: ${{ runner.os }}-jest-${{ steps.date.outputs.date }}
              path: '**/.jest_cache'