name: PR Code check

on: [push]

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
  
      - name: Restore node_modules cache
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          
      - name: Cache Jest cache
        id: cache-jest-cache
        uses: actions/cache@v2
        with:
            path: .jest-cache
            key: ${{ runner.os }}-${{ matrix.node-version }}-jest

      - name: Install dependencies 
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Restore node_modules cache
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      
      - name: Cache Jest cache
        id: cache-jest-cache
        uses: actions/cache@v2
        with:
            path: .jest-cache
            key: ${{ runner.os }}-${{ matrix.node-version }}-jest
      
      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1
      
      - name: Echo
        run: echo ${{steps.cpu-cores.outputs.count}}

      - name: Start test
        run: yarn test