name: Debug playwright issue

on:
    workflow_dispatch:
        inputs:
            fragment:
                type: string
                description: fragment name

jobs:
  install-dependencies:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium-headless-shell