name: PR Code check

on:
    workflow_dispatch:
        inputs:
            fragment:
                type: string
                description: fragment name
                required: true

jobs:
  install-dependencies:
    name: Install Playwright Browsers
    runs-on: ubuntu-latest
    steps:
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium-headless-shell